#Workflow for Continuous Deployment
name: Continuous Deployment

# Triggers the workflow on push or pull request events for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest # OS to execute the job in
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2 # Checks out the repository to the runner
  
    - name: Login / Build / Deploy
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Stores the Heroku API Key as an environment variable. Uses github secrets so that it is not exposed
        HEROKU_APP_NAME: ${{ 'smart-greenhouse-data-server' }} # Stores the heroku app name as an environment variable
        
    # 1. Change working directory to root of the solution where the dockerfile is located
    # 2. Log in to heroku container registry, automatically uses the environment variable defined previously
    # 3. Build the docker image using Dockerfile and push it to Heroku container registry of our app
    # 4. Release the image
      run: |
        cd SEP4DataWarehouse
        echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
        heroku container:push -a $HEROKU_APP_NAME web
        heroku container:release -a $HEROKU_APP_NAME web
