#Workflow for Continuous Deployment
name: Continuous Deployment

# Triggers the workflow on push or pull request events for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest # OS to execute the job in
    steps:
    
    - name: Clone
      uses: actions/checkout@v2 # Clones the repository to the runner
  
    - name: Login / Build / Deploy
      env:
        HEROKU_API_KEY: ${{ '7667c5b7-c508-4df2-ace1-3169ab139081' }}  # Stores the Heroku API Key as an environment variable
        
    # 1. Change working directory to root of the solution where the dockerfile is located
    # 2. Log in to heroku container registry, automatically uses the environment variable defined previously
    # 3. Build the docker image using Dockerfile and push it to Heroku container registry of our app
    # 4. Release the image
      run: |
        cd SEP4DataWarehouse
        heroku container:login
        heroku container:push -a smart-greenhouse-data-server web
        heroku container:release -a smart-greenhouse-data-server web
